### ISSUE TITLE
Can't resolve 'autobind-decorator'

### ISSUE THREAD

**Issue by ronrichard1984** [xurei/react-jotform-embed#1]
Anybody help me please to fix this:

./node_modules/react-jotform-embed/lib/react-jotform-embed.js
Module not found: Can't resolve 'autobind-decorator' in 'D:\wamp\www\wordpress\ronnie\sprinterrentalsusa_react\node_modules\react-jotform-embed\lib'

**Comment by xurei** [comment]
I just updated the version to 1.0.4 and removed the dependency. Can you try it and tell me if this works now ?
