### ISSUE TITLE
Missing module target file

### ISSUE THREAD

**Issue by cncolder** [xurei/react-jotform-embed#12]
Hi, There is a module field in package.json, but the target file is missing.

`"module": "lib/module/react-jotform-embed.js",`

https://unpkg.com/browse/react-jotform-embed@1.1.1/lib/

**Comment by xurei** [comment]
Thanks for the feedback. I don't have much time to spend on this project right now, but feel free to make a pull request fixing the issue (I don't think it's very complicated). I'll merge it in the project :-)

If you don't have time either, I'll eventually fix it, but right now I can't tell you when.
